In [1]:
import pandas as pd
from prophet import Prophet
import datetime

df = pd.read_csv('../data/daily-visits.csv')
df.ds = pd.to_datetime(df.ds)

df

             ds    y
0    2022-02-13  172
1    2022-02-12  195
2    2022-02-11  234
3    2022-02-10  232
4    2022-02-09  222
...         ...  ...
3571 2012-05-05  180
3572 2012-05-04  210
3573 2012-05-03  204
3574 2012-05-02  201
3575 2012-05-01  211

[3576 rows x 2 columns]

In [4]:
m = Prophet(interval_width=0.80)
m.fit(df)
future = m.make_future_dataframe(periods=14, freq='D')
forecast = m.predict(future.tail(14))
forecast = forecast[['ds','yhat', 'yhat_lower', 'yhat_upper']]
forecast

INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.

           ds        yhat  yhat_lower  yhat_upper
0  2022-02-14  257.012188  226.264978  287.695922
1  2022-02-15  238.945504  208.985221  269.250766
2  2022-02-16  232.273147  203.051039  261.356046
3  2022-02-17  231.457061  202.070016  262.671078
4  2022-02-18  235.709959  206.117613  265.181191
5  2022-02-19  202.218627  171.172098  232.473101
6  2022-02-20  201.139892  172.195667  231.919377
7  2022-02-21  263.986252  233.726513  293.117753
8  2022-02-22  245.865634  212.131829  277.389544
9  2022-02-23  239.094720  208.688049  268.802060
10 2022-02-24  238.134421  207.094585  270.068920
11 2022-02-25  242.196498  210.907492  272.494180
12 2022-02-26  208.466946  179.544189  239.613019
13 2022-02-27  207.102038  176.542961  238.593788